clc;
clear;
close all;
addpath(genpath(pwd));

params = set_params();

[gridProd, transitionProd] = tauchen( ...
    params.numGridPointsProd, ...
    params.persistenceProd, ...
    params.stdDevProd, ...
    params.meanProd * (1 - params.persistenceProd), ...
    4.0 ...
);

[v, exitPolicy, optLabor, optProfit] = solve_policy(params, gridProd, transitionProd, 2.0);         