params = set_params();

[gridProd, transitionProd] = tauchen( ...
    params.numGridPointsProd, ...
    params.persistenceProd, ...
    params.stdDevProd, ...
    params.meanProd * (1 - params.persistenceProd), ...
    4.0 ...
);

disp('Productivity grid:');
disp(gridProd(1:10));

disp('Productivity transition matrix:');
disp(transitionProd(1:10, 1:10));